version: '3'

services:
  apollo-gateway:
    build:
      context: ./gateway/
      dockerfile: Dockerfile
    env_file: ./gateway/.env.docker
    container_name: ms.gateway.apollo
    command: yarn start
    ports:
      - 4001:4001
    expose:
      - 4001
    networks:
      - ms-network
  authentication:
    build:
      context: ./service/authentication/
      dockerfile: Dockerfile
    env_file: ./service/authentication/.env.docker
    container_name: ms.service.authentication
    command: yarn start
    expose:
      - 4002
    networks:
      - ms-network
  # authentication-db:
  #   image: mongo:5.0.8
  #   container_name: ms.db.authentication
  #   volumes:
  #     # Bind the local directory to the container directory, here we keep our updating inside db even if we down the service
  #     - ~/service/.authentication/volumes/mongo:/data/db
  #   ports:
  #     - '27017:27017'
  #   networks:
  #     - ms-network

  # broker:
  #   image: rabbitmq:3.7.7-management
  #   container_name: broker
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #     - RABBITMQ_DEFAULT_VHOST=/
  #   networks:
      # - ms-network

networks:
  ms-network:
    driver: bridge
