type User {
  _id: ObjectId!
  email: String!
  firstname: String!
  lastname: String!
  createdAt: Float!
  updatedAt: Float!
  token: String
}

extend type Mutation {
  signUp(user: UserInput): User!
  login(email: String!, password: String!): User!
}

extend type Query {
  ping: String!
}

input UserInput {
  email: String!
  password: String!
  firstname: String!
  lastname: String!
  role: String!
}
